# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Sun Mar 24 18:08:32 2013
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.tblContents = QtGui.QTableWidget(self.centralwidget)
        self.tblContents.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tblContents.sizePolicy().hasHeightForWidth())
        self.tblContents.setSizePolicy(sizePolicy)
        self.tblContents.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tblContents.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tblContents.setVerticalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.tblContents.setHorizontalScrollMode(QtGui.QAbstractItemView.ScrollPerPixel)
        self.tblContents.setWordWrap(False)
        self.tblContents.setObjectName(_fromUtf8("tblContents"))
        self.tblContents.setColumnCount(0)
        self.tblContents.setRowCount(0)
        self.tblContents.horizontalHeader().setVisible(True)
        self.tblContents.verticalHeader().setVisible(True)
        self.horizontalLayout_3.addWidget(self.tblContents)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setContentsMargins(15, -1, -1, -1)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.lblSearch = QtGui.QLabel(self.centralwidget)
        self.lblSearch.setMinimumSize(QtCore.QSize(200, 0))
        self.lblSearch.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lblSearch.setObjectName(_fromUtf8("lblSearch"))
        self.verticalLayout.addWidget(self.lblSearch)
        self.txtSearch = QtGui.QLineEdit(self.centralwidget)
        self.txtSearch.setMinimumSize(QtCore.QSize(200, 0))
        self.txtSearch.setMaximumSize(QtCore.QSize(200, 16777215))
        self.txtSearch.setObjectName(_fromUtf8("txtSearch"))
        self.verticalLayout.addWidget(self.txtSearch)
        self.chkCaseInsensitive = QtGui.QCheckBox(self.centralwidget)
        self.chkCaseInsensitive.setMinimumSize(QtCore.QSize(200, 0))
        self.chkCaseInsensitive.setMaximumSize(QtCore.QSize(200, 16777215))
        self.chkCaseInsensitive.setChecked(True)
        self.chkCaseInsensitive.setObjectName(_fromUtf8("chkCaseInsensitive"))
        self.verticalLayout.addWidget(self.chkCaseInsensitive)
        self.chkWholeWord = QtGui.QCheckBox(self.centralwidget)
        self.chkWholeWord.setObjectName(_fromUtf8("chkWholeWord"))
        self.verticalLayout.addWidget(self.chkWholeWord)
        spacerItem = QtGui.QSpacerItem(200, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.lblColumns = QtGui.QLabel(self.centralwidget)
        self.lblColumns.setMinimumSize(QtCore.QSize(200, 0))
        self.lblColumns.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lblColumns.setObjectName(_fromUtf8("lblColumns"))
        self.verticalLayout.addWidget(self.lblColumns)
        self.lstColumns = QtGui.QListWidget(self.centralwidget)
        self.lstColumns.setMinimumSize(QtCore.QSize(200, 0))
        self.lstColumns.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lstColumns.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.lstColumns.setObjectName(_fromUtf8("lstColumns"))
        self.verticalLayout.addWidget(self.lstColumns)
        spacerItem1 = QtGui.QSpacerItem(200, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.lblResults = QtGui.QLabel(self.centralwidget)
        self.lblResults.setMinimumSize(QtCore.QSize(200, 0))
        self.lblResults.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lblResults.setObjectName(_fromUtf8("lblResults"))
        self.verticalLayout.addWidget(self.lblResults)
        self.lstSearchResults = QtGui.QListWidget(self.centralwidget)
        self.lstSearchResults.setMinimumSize(QtCore.QSize(200, 0))
        self.lstSearchResults.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lstSearchResults.setObjectName(_fromUtf8("lstSearchResults"))
        self.verticalLayout.addWidget(self.lstSearchResults)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuSettings_2 = QtGui.QMenu(self.menuBar)
        self.menuSettings_2.setObjectName(_fromUtf8("menuSettings_2"))
        self.menuHelp = QtGui.QMenu(self.menuBar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.actionOpen_file = QtGui.QAction(MainWindow)
        self.actionOpen_file.setObjectName(_fromUtf8("actionOpen_file"))
        self.actionClose_file = QtGui.QAction(MainWindow)
        self.actionClose_file.setObjectName(_fromUtf8("actionClose_file"))
        self.menuQuit = QtGui.QAction(MainWindow)
        self.menuQuit.setMenuRole(QtGui.QAction.TextHeuristicRole)
        self.menuQuit.setObjectName(_fromUtf8("menuQuit"))
        self.actionComma = QtGui.QAction(MainWindow)
        self.actionComma.setCheckable(True)
        self.actionComma.setChecked(True)
        self.actionComma.setObjectName(_fromUtf8("actionComma"))
        self.actionSemicolon = QtGui.QAction(MainWindow)
        self.actionSemicolon.setCheckable(True)
        self.actionSemicolon.setObjectName(_fromUtf8("actionSemicolon"))
        self.actionSpace = QtGui.QAction(MainWindow)
        self.actionSpace.setCheckable(True)
        self.actionSpace.setObjectName(_fromUtf8("actionSpace"))
        self.actionTab = QtGui.QAction(MainWindow)
        self.actionTab.setCheckable(True)
        self.actionTab.setObjectName(_fromUtf8("actionTab"))
        self.actionDouble_quote = QtGui.QAction(MainWindow)
        self.actionDouble_quote.setObjectName(_fromUtf8("actionDouble_quote"))
        self.actionSingle_quote = QtGui.QAction(MainWindow)
        self.actionSingle_quote.setObjectName(_fromUtf8("actionSingle_quote"))
        self.actionPreferences = QtGui.QAction(MainWindow)
        self.actionPreferences.setObjectName(_fromUtf8("actionPreferences"))
        self.menuSettings = QtGui.QAction(MainWindow)
        self.menuSettings.setObjectName(_fromUtf8("menuSettings"))
        self.menuOpen = QtGui.QAction(MainWindow)
        self.menuOpen.setObjectName(_fromUtf8("menuOpen"))
        self.menuFieldSeparator = QtGui.QAction(MainWindow)
        self.menuFieldSeparator.setObjectName(_fromUtf8("menuFieldSeparator"))
        self.menuTextDelimiter = QtGui.QAction(MainWindow)
        self.menuTextDelimiter.setObjectName(_fromUtf8("menuTextDelimiter"))
        self.menuVerticalHeader = QtGui.QAction(MainWindow)
        self.menuVerticalHeader.setCheckable(True)
        self.menuVerticalHeader.setChecked(True)
        self.menuVerticalHeader.setObjectName(_fromUtf8("menuVerticalHeader"))
        self.menuHorizontalHeader = QtGui.QAction(MainWindow)
        self.menuHorizontalHeader.setCheckable(True)
        self.menuHorizontalHeader.setChecked(True)
        self.menuHorizontalHeader.setObjectName(_fromUtf8("menuHorizontalHeader"))
        self.menuHeaderLabels = QtGui.QAction(MainWindow)
        self.menuHeaderLabels.setCheckable(True)
        self.menuHeaderLabels.setObjectName(_fromUtf8("menuHeaderLabels"))
        self.menuAboutMessage = QtGui.QAction(MainWindow)
        self.menuAboutMessage.setObjectName(_fromUtf8("menuAboutMessage"))
        self.menuFile.addAction(self.menuOpen)
        self.menuFile.addAction(self.menuQuit)
        self.menuSettings_2.addAction(self.menuFieldSeparator)
        self.menuSettings_2.addAction(self.menuTextDelimiter)
        self.menuSettings_2.addSeparator()
        self.menuSettings_2.addAction(self.menuHorizontalHeader)
        self.menuSettings_2.addAction(self.menuVerticalHeader)
        self.menuSettings_2.addSeparator()
        self.menuSettings_2.addAction(self.menuHeaderLabels)
        self.menuHelp.addAction(self.menuAboutMessage)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuSettings_2.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tblContents, self.txtSearch)
        MainWindow.setTabOrder(self.txtSearch, self.chkCaseInsensitive)
        MainWindow.setTabOrder(self.chkCaseInsensitive, self.lstColumns)
        MainWindow.setTabOrder(self.lstColumns, self.lstSearchResults)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "bwCSV", None))
        self.lblSearch.setText(_translate("MainWindow", "Search:", None))
        self.chkCaseInsensitive.setText(_translate("MainWindow", "Case insensitive", None))
        self.chkWholeWord.setText(_translate("MainWindow", "Whole word search", None))
        self.lblColumns.setText(_translate("MainWindow", "Search columns:", None))
        self.lblResults.setText(_translate("MainWindow", "Search results:", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuSettings_2.setTitle(_translate("MainWindow", "Settings", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.actionOpen_file.setText(_translate("MainWindow", "Open file...", None))
        self.actionClose_file.setText(_translate("MainWindow", "Close file", None))
        self.menuQuit.setText(_translate("MainWindow", "Exit", None))
        self.actionComma.setText(_translate("MainWindow", "Comma", None))
        self.actionSemicolon.setText(_translate("MainWindow", "Semicolon", None))
        self.actionSpace.setText(_translate("MainWindow", "Space", None))
        self.actionTab.setText(_translate("MainWindow", "Tab", None))
        self.actionDouble_quote.setText(_translate("MainWindow", "Double-quote", None))
        self.actionSingle_quote.setText(_translate("MainWindow", "Single-quote", None))
        self.actionPreferences.setText(_translate("MainWindow", "Preferences...", None))
        self.menuSettings.setText(_translate("MainWindow", "Settings...", None))
        self.menuOpen.setText(_translate("MainWindow", "Open...", None))
        self.menuFieldSeparator.setText(_translate("MainWindow", "Field separator...", None))
        self.menuTextDelimiter.setText(_translate("MainWindow", "Text delimiter...", None))
        self.menuVerticalHeader.setText(_translate("MainWindow", "Vertical header", None))
        self.menuHorizontalHeader.setText(_translate("MainWindow", "Horizontal header", None))
        self.menuHeaderLabels.setText(_translate("MainWindow", "Set header labels from first line", None))
        self.menuAboutMessage.setText(_translate("MainWindow", "About...", None))

import icons_rc
